%YAML:1.0
cameras:
    - {T_SC:
       [-0.09797776, -0.43383447, 0.89564949, 0.2126293,
        0.9951771, -0.03838393, 0.09027298, -0.08184055,
        -0.00478498, 0.90017461, 0.4355029, 0.04127858,
        0.0, 0.0, 0.0, 1.0],
       image_dimension: [640, 360],
       distortion_coefficients: [-0.009323672549944153, -0.05556407762990372, 0.060139423599591464, -0.024717760431210257],
       distortion_type: equidistant,
       focal_length: [350.66111904406205, 350.6980567036906],
       principal_point: [316.78970218808206, 183.47578133031405],
       cam_model: pinhole,
       camera_type: gray,
       slam_use: okvis}
 
    - {T_SC:
       [-0.01486365, -0.44145802, 0.89715879, 0.2036199,
        0.99979845, -0.01867199, 0.00737635, 0.11297583,
        0.01349539, 0.89708761, 0.44164658, 0.04424307,
        0.0, 0.0, 0.0, 1.0],
       image_dimension: [640, 360],
       distortion_coefficients: [-0.00602256244630935, -0.07287635661793096, 0.10780410695065011, -0.05806209375975833],
       distortion_type: equidistant,
       focal_length: [349.9555126739141, 349.99866888455773],
       principal_point: [315.49754197018336, 168.51912216806244],
       cam_model: pinhole,
       camera_type: gray,
       slam_use: okvis}
 
camera_parameters:
    timestamp_tolerance: 0.01 # [s] stereo frame out-of-sync tolerance
    sync_cameras: [0,1] # the cameras that will be synchronised
    image_delay:  0.024553912 # [s] timestamp_camera_correct = timestamp_camera - image_delay
    online_calibration:
        do_extrinsics: true # Do we online-calibrate extrinsics?
        do_extrinsics_final_ba: false # Do we calibrate extrinsics in final BA?
        sigma_r: 0.01 # T_SCi position prior stdev [m]
        sigma_alpha: 0.1 # T_SCi orientation prior stdev [rad]
        sigma_r_final_ba: 0.03 # T_SCi position prior stdev in final BA [m]
        sigma_alpha_final_ba: 0.3 # T_SCi orientation prior stdev in final BA [rad]
    #image_masks:
    #    - camera_index: 0
    #      regions:
    #          - [0, 0, 100, 100]      # top-left corner
    #          - [540, 0, 100, 100]    # top-right corner
    #    - camera_index: 1
    #      regions:
    #          - [0, 0, 100, 100]      # top-left corner
    #          - [540, 0, 100, 100]    # top-right corner
 
imu_parameters:
    use: true
    a_max: 163.84 # acceleration saturation [m/s^2]
    g_max: 5.72 # gyro saturation [rad/s]
    sigma_g_c: 6.519797189220827e-04
    sigma_a_c: 0.011220644611759998     # accelerometer noise density [m/s^2/sqrt(Hz)]
    sigma_bg: 4.027038e-03  # gyro bias prior [rad/s]
    sigma_ba: 4.827057e-02 # accelerometer bias prior [m/s^2]
    sigma_gw_c: 3.5772073471410063e-05 # gyro drift noise density [rad/s^s/sqrt(Hz)]
    sigma_aw_c: 3.940336355177357e-04 # accelerometer drift noise density [m/s^2/sqrt(Hz)]
    g: 9.81007 # Earth's acceleration due to gravity [m/s^2]
    #g0: [-3.817197e-04, -4.621183e-04, 5.725522e-05]  # initial gyroscope bias [rad/s]
    #a0: [4.121590e-03, 8.667063e-02, 9.666414e-03]  # initial accelerometer bias [m/s^2]
    g0: [0.0, 0.0, 0.0] # initial gyroscope bias [rad/s]
    a0: [0.0, 0.0, 0.0] # initial accelerometer bias [m/s^2]
 
    T_BS:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]
 
frontend_parameters:
    detection_threshold: 38.0 #42.0 # detection threshold. By default the uniformity radius in pixels
    absolute_threshold: 150.0 # absolute Harris corner threshold (noise floor)
    matching_threshold: 60.0 # BRISK descriptor matching threshold
    octaves: 0 # number of octaves for detection. 0 means single-scale at highest resolution
    max_num_keypoints: 700 # restrict to a maximum of this many keypoints per image (strongest ones)
    keyframe_overlap: 0.60 # minimum field-of-view overlap
    use_cnn: false # use the CNN (if available) to filter out dynamic content / sky
    parallelise_detection: true # Run parallel detect & describe.
    num_matching_threads: 4 # Parallelise matching with this number of threads.
 
# estimator parameters
estimator_parameters:
    num_keyframes: 5 # number of keyframes in optimisation window
    num_loop_closure_frames: 3 # number of loop closure frames in optimisation window
    num_imu_frames: 3 # number of frames linked by most recent nonlinear IMU error terms
    do_loop_closures: true # whether to do VI-SLAM or VIO
    do_final_ba: false # Whether to run a full final BA
    enforce_realtime: false # whether to limit the time budget for optimisation
    realtime_min_iterations: 3 # minimum number of iterations always performed
    realtime_max_iterations: 10 # never do more than these, even if not converged
    realtime_time_limit: 0.035 # time budget for realtime optimisation [s]
    realtime_num_threads: 3 # number of threads for the realtime optimisation
    full_graph_iterations: 15 # don't do more than these for the full (background) optimisation
    full_graph_num_threads: 3 # number of threads for the full (background) optimisation
 
# some options for how and what to output
output_parameters:
    display_matches: true  # displays debug video and matches. May be slow.
    display_overhead: false # debug overhead image. Is slow.
 